export const COMPANY_ADDRESS = {
  REGION: 'Московская обл.',
  CITY: 'г. Звенигород',
  STREET: 'ул. Чехова',
  HOUSE: 'д. 13А',
  POSTAL_CODE: '143180',
};
export const COMPANY_BASE_ADDRESS = [COMPANY_ADDRESS.CITY, COMPANY_ADDRESS.STREET, COMPANY_ADDRESS.HOUSE].join(', ');
export const COMPANY_FULL_ADDRESS = [
  COMPANY_ADDRESS.POSTAL_CODE,
  COMPANY_ADDRESS.REGION,
  COMPANY_ADDRESS.CITY,
  COMPANY_ADDRESS.STREET,
  COMPANY_ADDRESS.HOUSE,
].join(', ');
