name: Deploy to Yandex Object Storage

on:
  push:
    branches:
      - main

env:
  NODE_VERSION: '18'
  S3_BUCKET: 'zvenfit-frontend'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm ci

      - name: Run linter
        run: |
          npm run lint || exit 1

      - name: Build app
        run: |
          npm run build || exit 1

      - name: Upload files to Yandex Object Storage
        uses: docker://amazon/aws-cli:2.25.1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.YC_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.YC_SECRET_ACCESS_KEY }}
          AWS_REGION: ru-1
          AWS_ENDPOINT_URL: https://storage.yandexcloud.net
        with:
          args: s3 sync ./dist s3://${{ env.S3_BUCKET }} --delete --debug

#      - name: Upload files to Yandex Object Storage
#        run: |
#          aws --endpoint-url=https://storage.yandexcloud.net s3 sync ./dist s3://${{ env.S3_BUCKET }} --delete --debug
